-   id: find-alpha-dependencies
    name: find-alpha-dependencies
    description: This checks for alpha dependencies in non-alpha folders across repo 
    entry: find_alpha_dependencies
    language: script
    files: '^(.*/)'
